# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  push:
    branches:
      - "master"

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Install 8.1 SDK
      shell: powershell
      run: |
        Start-Process -Wait ./sdk/sdksetup.exe -ArgumentList "/q", "/norestart", "/features", "OptionId.WindowsDesktopSoftwareDevelopmentKit", "OptionId.NetFxSoftwareDevelopmentKit"

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m "/p:Platform=x64;Configuration=Debug" "./tbf.sln"

    - uses: actions/upload-artifact@v4
      with:
        name: tbfix
        path: build/debug/*
        retention-days: 7
